// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// CasbinRepository is an autogenerated mock type for the CasbinRepository type
type CasbinRepository struct {
	mock.Mock
}

// DeleteRoleRules provides a mock function with given fields: tx, roleCode
func (_m *CasbinRepository) DeleteRoleRules(tx *gorm.DB, roleCode string) error {
	ret := _m.Called(tx, roleCode)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoleRules")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) error); ok {
		r0 = rf(tx, roleCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCasbinRepository creates a new instance of CasbinRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCasbinRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CasbinRepository {
	mock := &CasbinRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
