basePath: /
definitions:
  common.Response:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 数据
      message:
        description: 消息
        type: string
    type: object
  dto.RoleCreateRequest:
    properties:
      code:
        description: 角色编码
        example: ADMIN
        type: string
      description:
        description: 角色描述
        example: 系统管理员角色
        type: string
      name:
        description: 角色名称
        example: 管理员
        type: string
    required:
    - code
    - name
    type: object
  dto.RoleListResponse:
    properties:
      list:
        description: 角色列表
        items:
          $ref: '#/definitions/dto.RoleResponse'
        type: array
      total:
        description: 总数
        example: 100
        type: integer
    type: object
  dto.RoleResponse:
    properties:
      code:
        description: 角色编码
        example: ADMIN
        type: string
      created_at:
        description: 创建时间
        example: "2023-01-01 12:00:00"
        type: string
      description:
        description: 角色描述
        example: 系统管理员角色
        type: string
      id:
        description: 角色ID
        example: 1
        type: integer
      is_system:
        description: 是否为系统角色
        example: true
        type: boolean
      name:
        description: 角色名称
        example: 管理员
        type: string
      status:
        description: 状态：1-启用，0-禁用
        example: 1
        type: integer
    type: object
  dto.RoleUpdateRequest:
    properties:
      description:
        description: 角色描述
        example: 系统管理员角色
        type: string
      id:
        description: 角色ID
        example: 1
        type: integer
      name:
        description: 角色名称
        example: 管理员
        type: string
      status:
        description: 状态：1-启用，0-禁用
        example: 1
        type: integer
    required:
    - id
    - name
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: 企业级对象存储系统后端 API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: OSS-Backend API
  version: "1.0"
paths:
  /api/oss/role/create:
    post:
      consumes:
      - application/json
      description: 创建一个新角色
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 角色信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RoleCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/common.Response'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/common.Response'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/common.Response'
        "500":
          description: 内部服务器错误
          schema:
            $ref: '#/definitions/common.Response'
      summary: 创建角色
      tags:
      - 角色管理
  /api/oss/role/delete/{id}:
    get:
      consumes:
      - application/json
      description: 删除指定ID的角色
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 角色ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/common.Response'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/common.Response'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/common.Response'
        "500":
          description: 内部服务器错误
          schema:
            $ref: '#/definitions/common.Response'
      summary: 删除角色
      tags:
      - 角色管理
  /api/oss/role/detail/{id}:
    get:
      consumes:
      - application/json
      description: 根据ID获取角色详情
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 角色ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.RoleResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/common.Response'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/common.Response'
        "500":
          description: 内部服务器错误
          schema:
            $ref: '#/definitions/common.Response'
      summary: 获取角色详情
      tags:
      - 角色管理
  /api/oss/role/list:
    get:
      consumes:
      - application/json
      description: 根据条件获取角色列表
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 角色名称，模糊查询
        in: query
        name: name
        type: string
      - description: 状态：1-启用，0-禁用
        enum:
        - 0
        - 1
        in: query
        name: status
        type: integer
      - description: 页码，默认1
        in: query
        name: page
        type: integer
      - description: 每页数量，默认10
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.RoleListResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/common.Response'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/common.Response'
        "500":
          description: 内部服务器错误
          schema:
            $ref: '#/definitions/common.Response'
      summary: 获取角色列表
      tags:
      - 角色管理
  /api/oss/role/update:
    post:
      consumes:
      - application/json
      description: 更新角色信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 角色信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RoleUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/common.Response'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/common.Response'
        "401":
          description: 未授权
          schema:
            $ref: '#/definitions/common.Response'
        "500":
          description: 内部服务器错误
          schema:
            $ref: '#/definitions/common.Response'
      summary: 更新角色
      tags:
      - 角色管理
schemes:
- http
- https
swagger: "2.0"
